### ISSUE TITLE
Crash on Typing event

### ISSUE THREAD

**Issue by shrx** [topisani/Discurses#12]
Steps to reproduce:
1) Go to a channel
2) Start typing - a "user is typing" message is displayed
3) Post typed string (press return) - crash happens

I couldn't select the error message to copy it, so here's a screenshot:

![screenshot_2016-10-10_11-14-52](https://cloud.githubusercontent.com/assets/810337/19231573/0530bfd6-8edb-11e6-80bf-2c6f137fa0ce.png)

The typed string is still posted.

Crash only happens on some servers, not all.

**Comment by tkerdonc** [comment]
It seems that this happens when no overrides (mutes and such) were configured on the server, it is just a matter of checking for the returned value of this data.get

**Comment by tkerdonc** [comment]
Submitted PR #35
