### ISSUE TITLE
localStorage to get token no longer exists.

### ISSUE THREAD

**Issue by Demonstrandum** [topisani/Discurses#18]
```javascript
> localStorage.getItem("token")
Uncaught ReferenceError: localStorage is not defined
    at <anonymous>:1:1
(anonymous) @ VM943:1
```
Unable to get token for `.yaml` file, the localStorage function is no longer there.

**Comment by Demonstrandum** [comment]
Made a pull request on new method of retrieving token here: https://github.com/topisani/Discurses/pull/19

**Comment by undying-fish** [comment]
Discord's response in my twitter DMs:

"Sorry, but we have no affiliation with that site or program, so we won't be able to recommend anything in regards to it."

**Comment by Demonstrandum** [comment]
@undying-fish Yeah, this is @topisani's program, not Discords so naturally they cannot help. It's just that in the README the method of retrieving the token is dated. 

I've found a new way and added it to the README in pull request #19.

**Comment by undying-fish** [comment]
Thanks, I've just got this working. This issue can be closed now.
