### ISSUE TITLE
Forbidden channels

### ISSUE THREAD

**Issue by glitchassassin** [topisani/Discurses#29]
When selecting a server (but no channel), you can send messages (in my case, they show up on the default #general channel) but you don't see any messages in the list (because no channels are selected).

I suggest that if a server is selected, but not a channel, a default channel should be selected for viewing as well as for sending messages.

Thanks for the project!

**Comment by Ge0** [comment]
Hi!

It's been a few weeks since I haven't used discursed. I am not sure I'll have the time to dev this feature but if you think you could do so, be my guest!

**Comment by glitchassassin** [comment]
So after troubleshooting this for a while, it turns out the issue wasn't having no channel selected; instead, the default channel just happened to be one I didn't have access to, which was throwing a Forbidden error - and the client's background thread was crashing instead of handling it.

I'm creating a pull request with my fix.
