### ISSUE TITLE
Install-Problems

### ISSUE THREAD

**Issue by tionis** [topisani/Discurses#33]
I just cant get the application started, even after checking all dependencies and similar.
npm should add the command discurses, right?

**Comment by Ge0** [comment]
How do you install discurses? Try `pip install discurses`, as said in the README file.

**Comment by tionis** [comment]
@Ge0 Already tried that, the install ends in an error-code other than the pip3 install who states that discurses is installed

**Comment by Ge0** [comment]
And what happens when you type `discurses` in the terminal?

I'm not sure npm is ever needed here. I'm saying this because I'm not the original developer (cc @topisani).

**Comment by tionis** [comment]
@Ge0 discurses: command not found 
(system is a 64-bit ubuntu)

**Comment by topisani** [comment]
`pip` uses python 2, which wont work. The other problem sounds like the pip install path is not correctly added to your `PATH` environment variable. Google might help you with that, im not sure where pip installs stuff on ubuntu.

No, npm is not needed at all

**Comment by snixon** [comment]
If you installed via pip as your user, it probably created a directory in $HOME/.local/bin/  and dropped the file there.

Try this to get it into your path.
`export PATH=$PATH:$HOME/.local/bin`

if discurses shows up, now you have your answer, edit your conf in either $HOME/.profile or $HOME/.bashrc to add the $HOME/.local/bin to your users path.
