### ISSUE TITLE
Proposed UI Changes

### ISSUE THREAD

**Issue by sirplatypos** [topisani/Discurses#37]
When I first log in, I have a choice of servers and channels.  If I select a server, everything works.  If I expand the tree and select a specific channel, then pushing the down arrow to switch channels does not work. It only displays the current channel.  Alt + s still works to go back though.  I am not sure if this is a bug, or if it was intended.  At the same time, if I select a server but not a channel at the start, all messages from all channels are shown on one screen, even though I am sending to only one channel.  I like this, but again am not sure if it is a bug.  (Not sending a picture of that for privacy reasons).
![screenshot from 2018-04-02 18-09-57](https://user-images.githubusercontent.com/32854229/38219003-d19b9c8e-36a1-11e8-83ea-eed77a59483d.png)

**Comment by topisani** [comment]
In discurses you can view more than one channel at a time. When you select a server it views them all at once.

pressing the down arrow just switches between the currently visible channels. You should also try running it from a git clone, i havent gotten around to updating the pip version yet

**Comment by topisani** [comment]
pip is updated now, let me know how that goes

**Comment by sirplatypos** [comment]
Well, it mostly works now, with a few issues.  First off, there is now this white bar, as shown below.  This looks very out of place.  Second, when viewing an entire server, by prefixing all of the channel names with the server name, it makes it impossible to see which channel the messages are coming from.  It is also an inconvenience in the channel switcher.  
On the other subject, other than viewing an entire server, I have not figured out if it is possible to selectively view multiple but not all channels.  Was the original intent to use the channel switcher on the bottom only when viewing an entire server?
Two more possible improvements are having the memberlist only show the members of the current channel, and fixing the member colors to grey out offline members and leave red for the people on dnd.

![screenshot](https://user-images.githubusercontent.com/32854229/38224614-c5a757fc-36be-11e8-9269-12b7bbf6d6b0.png)


I'm sorry to bombard you with so many things, I'm just desperate for a cli and this is the best and most active one I have found.
