### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by Ge0** [topisani/Discurses#42]
from @warshanks

> So I tried to reinstall and I got this 
> 
> ```
> pip3.6 install discurses
> Collecting discurses
>   Using cached discurses-0.3.0.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-swwsrz2u/discurses/setup.py", line 5, in <module>
>         from pip.req import parse_requirements
>     ModuleNotFoundError: No module named 'pip.req'
> ```
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-swwsrz2u/discurses/

The concerned line should not appear in setup.py anyway.

Still, I have no problem while setting up discurses.

**Comment by Ge0** [comment]
It's fixed by the way.

**Comment by mvkalsbeek** [comment]
Using `pip` to install Discurses threw an error about the running Python version for me as well. After installing `python3-pip` and using `pip3` to install Discurses the installation worked without error. Shouldn't the installation instructions (readme) be adjusted for this?
