### ISSUE TITLE
Error when installing with pip3.6 or python 3.6 -m pip

### ISSUE THREAD

**Issue by EzraJ** [topisani/Discurses#47]
I'm running
sudo -H pip3.6 install discurses
and I get the error:
File "<string>", line 1, in <module>
File "/tmp/pip-install-gawvt9ev/discurses/setup.py", line 5, in <module>
   from pip.req import parse_requirements
ModuleNotFoundError: No module named 'pip.req'

_____________________________________________
Command "python setup.py egg_info" failed with error code 1 in /tmp/install/gawvt9ev/discurses/

**Comment by Ge0** [comment]
Hi!

I have updated discurses to v0.3.3. Please update it on your side and tell me if the problem still happens. It should normally be ok.

**Comment by tkduman** [comment]
@Ge0 I'm getting this:

```
root@server [/usr/src/Python-3.6.5]# python3.6 -m pip install discurses
Collecting discurses
  Using cached https://files.pythonhosted.org/packages/cf/86/0b3108feb9a2170650d985ffb58a743ed402cc5138a2605812deef9e2437/discurses-0.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8gur6q81/discurses/setup.py", line 31, in <module>
        long_description=get_readme(),
      File "/tmp/pip-install-8gur6q81/discurses/setup.py", line 15, in get_readme
        return fileobj.read()
      File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 177: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-8gur6q81/discurses/
```

**Comment by EzraJ** [comment]
Now i'm having this error:

File "/usr/local/lib/python3.6/dist-packages/discurses/ui/message_list.py" in line 4, in <module>
import urwid
ModuleNotFoundError: urwid

When I run 
sudo -H(With or without sudo) python3.6 -m pip install urwid
pip instal urwid
pip3.6 install urwid
etc

**Comment by EzraJ** [comment]
Never mind, I just reinstalled urwid and it started working. Thanks!

**Comment by Ge0** [comment]
@tkduman Please open a new issue for your bug. I close this one since it has been fixed.
