### ISSUE TITLE
"Yank" command doesn't do anything?

### ISSUE THREAD

**Issue by MysteryPig** [topisani/Discurses#51]
After selecting a message and pressing Y, it displayed an error saying I needed xclip. Having installed xclip, doing this doesn't change the contents of xclip at all.

**Comment by Ge0** [comment]
@topisani Any clue?

**Comment by topisani** [comment]
try both `shift+insert` and `ctrl+v` ? I think the copy command is defined in `config.py` and can be set to whatever, try playing around with that.

**Comment by MysteryPig** [comment]
Never mind, I just had xclip configured oddly.
