### ISSUE TITLE
Notify-send spam

### ISSUE THREAD

**Issue by LarBob** [topisani/Discurses#54]
On platforms without notify-send (e.g. macOS), "sh: notify-send: command not found" gets spammed within Discurses.

**Comment by Ge0** [comment]
Nice catch,

I think it's even dangerous to use `os.system` this way (I mean, with `$PATH` tricking).

Moreover, I think this should not be used in a few cases (like when you don't have any X server running...).

**Comment by blade2005** [comment]
May I recommend taking a look at https://pypi.org/project/notify2/

I'm not sure it works under macos. But I am runnin discurses headless and that notify spam is annoying.

I also don't have a mac to test notify2 on

**Comment by blade2005** [comment]
sorry for the double post but I wanted to make sure this got seen as well. 

Should this be addressed by making it possible to turn off notifications, making it an optional dependency for notify2 or whatever library is ultimately used. This means we fix the immediate issue of issues with redraws for people using terminals and don't have a notify. It then allows more time to approach this fix correctly without being rushed.
