### ISSUE TITLE
Can't use self tokens anymore

### ISSUE THREAD

**Issue by piqle** [topisani/Discurses#62]
Due to updated ToS you're unable to pull your own token anymore.

Will there be a workaround for this?

**Comment by BrianD91** [comment]
Actually  you ARE still able to get your token.

I've only tested this in chromium browser.
1. Open Browser
2. Navigate to https://discordapp.com/channels/@me
3. Open Dev Tools (F12)
3. Click the "Application" tab
3. Under "Storage" open the "Local Storage" Drop down and click on the discord url item there
4. at the bottom of the list you shouldnt see the token item
5. refresh the page, and if you're quick you WILL be able to see the token pop up and you will be able to copy and paste it into the .yaml as required

**Comment by piqle** [comment]
Thanks :)

**Comment by ekimekim** [comment]
Just found this. Any chance of updating the README?
