### ISSUE TITLE
Cant import Channel from discord

### ISSUE THREAD

**Issue by Gabgab2003** [topisani/Discurses#65]
When i try to start discurses i get this error:
```
➜ discurses
Traceback (most recent call last):
  File "/usr/bin/discurses", line 7, in <module>
    from discurses.__main__ import main
  File "/usr/lib/python3.7/site-packages/discurses/__main__.py", line 1, in <module>
    from . import discord
  File "/usr/lib/python3.7/site-packages/discurses/discord.py", line 7, in <module>
    from discord import Channel, Message
ImportError: cannot import name 'Channel' from 'discord' (/usr/lib/python3.7/site-packages/discord/__init__.py)

```

**Comment by HikaruNevermore** [comment]
I am getting a similar error as well

**Comment by Vexxii** [comment]
If you're using Python 3.7, uninstall it and install Python 3.6
Also, make sure you installed discord.py just to be safe:
`python3 -m pip install -U discord.py`

See:
https://github.com/Rapptz/discord.py/issues/1565
https://github.com/Rapptz/discord.py/issues/1249

**Comment by snus-kin** [comment]
Hey @topisani @Ge0 I think this can be closed as well?

**Comment by lukecograph** [comment]
I've followed all the instructions here as well as the readme, and still am getting this error also. Python 3.6.7 on Ubuntu 18.04
