### ISSUE TITLE
python3.7 install fails

### ISSUE THREAD

**Issue by UlisseMini** [topisani/Discurses#77]
When i run `pip install discurses` i get `discurses requires Python '>=3.6, !=3.7.*' but the running Python is 3.7.3`

Using arch BTW

**Comment by snus-kin** [comment]
Yes, this program doesn't work with 3.7.* at all, this is a `discord.py` issue upstream, it's only compatible with 3.6

**Comment by techied** [comment]
Yes. That's discurses telling you, any Python version greater than or equal to 3.6 is allowed but not any 3.7.x version, because Discord.py, the underlying API library, doesn't support that python version.
