### ISSUE TITLE
Discurses uses way too much RAM

### ISSUE THREAD

**Issue by ghost** [topisani/Discurses#81]
I'm unable to use the program as my ssh host only has 2GB RAM and the kernel always kills discurses every time I try to run it:

```
[6429792.083077] Out of memory: Kill process 21135 (discurses) score 398 or sacrifice child
[6429792.090599] Killed process 21135 (discurses) total-vm:1115996kB, anon-rss:796892kB, file-rss:0kB, shmem-rss:0kB
```

This is exactly the reason I cannot use the website version either... IMO 800+ megabytes for a text chat client is unacceptable.

Is there anything that can be done?

**Comment by topisani** [comment]
Idk, it's not really under development anymore. Try one that isn't written in python maybe...

**Comment by ghost** [comment]
Oh really? Hmm, it seems most/all of the nice looking ones are now abandoned. Oh well...
